### ISSUE TITLE
Animations support?

### ISSUE THREAD

**Issue by dandan2611** [juliarn/NPC-Lib#100]
Hello!

I've been using NPC-Lib v2 for a project, now it's time to move to v3 (hello 1.19). Without documentation, it is pretty hard to know all the features implemented/not implemented yet in the new version of the library.

Are the npc animations implemented yet? (crouched, sitting...) If so, where are they located? If not, I could take some time to make a PR in order to make this possible :)

Have a great day!

**Comment by derklaro** [comment]
atm animations can only be send via the packet adapter directly (available from the platform). An example usage is:
`npc.platform().packetFactory().createAnimationPacket(EntityAnimation.SWING_MAIN_ARM).schedule(player, npc);`.

There was a request to add methods to NPC for these packets as well, but I had no time yet to add those.

**Comment by dandan2611** [comment]
Thank you! Closing the issue.
