### ISSUE TITLE
Exmape to create NPCS

### ISSUE THREAD

**Issue by DevSnx** [juliarn/NPC-Lib#102]
Hey, you have any simple examples to create a NPC?

**Comment by kingOf0** [comment]
An example how to create a npc & pool for bukkit can be found here: [NPC Pool creation](https://github.com/CloudNetService/CloudNet-v3/blob/nightly/modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java#L63-L71), [NPC creation](https://github.com/CloudNetService/CloudNet-v3/blob/nightly/modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java#L75-L94), [NPC Event subscriptions](https://github.com/CloudNetService/CloudNet-v3/blob/nightly/modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java#L59-L62).

And here is a kotlin scratch. Works with beta v3 on 1.19.3.

```
import com.github.juliarn.npclib.api.Npc
import com.github.juliarn.npclib.api.NpcActionController
import com.github.juliarn.npclib.api.profile.Profile
import com.github.juliarn.npclib.bukkit.BukkitPlatform
import com.github.juliarn.npclib.bukkit.BukkitWorldAccessor
import com.github.juliarn.npclib.bukkit.util.BukkitPlatformUtil
import org.bukkit.Bukkit
import org.bukkit.Location
import java.util.*

val npcPlatform = BukkitPlatform.bukkitNpcPlatformBuilder()
    .extension(PLUGIN_INSTANCE)
    .actionController { builder ->
        builder
            .flag(NpcActionController.SPAWN_DISTANCE, 60)
            .flag(NpcActionController.IMITATE_DISTANCE, 16)
            .flag(NpcActionController.TAB_REMOVAL_TICKS, 20)
    }
    .worldAccessor(BukkitWorldAccessor.nameBasedAccessor())
    .build()

val location = Location(Bukkit.getWorld("world"), 0.0, 0.0, 0.0)

val npc = npcPlatform.newNpcBuilder()
    .position(BukkitPlatformUtil.positionFromBukkitLegacy(location))
    .profile(Profile.resolved("name", UUID.fromString("uuid")))
    .flag(Npc.LOOK_AT_PLAYER, false)
    .flag(Npc.HIT_WHEN_PLAYER_HITS, false)
    .flag(Npc.SNEAK_WHEN_PLAYER_SNEAKS, false)
    .buildAndTrack()
```

**Comment by derklaro** [comment]
I just added documentation and a bunch of code examples into the readme, feel free to leave feedback if something is missing.
