### ISSUE TITLE
Proper publishing

### ISSUE THREAD

**Issue by DasBabyPixel** [juliarn/NPC-Lib#113]
The groupId in the pom.xml is lowercase while the group for the repository is mixed-case. This creates fun like this:
![image](https://github.com/juliarn/NPC-Lib/assets/43410952/92a8aed7-c7df-41fc-b13d-ce58d8c580a9)
[Here](https://github.com/DasBabyPixel/NPC-Lib-Demo.git) is a demo project for the problem.
The master branch has the problem, the workaround branch uses [this](https://stackoverflow.com/a/57616431) workaround.
Even though with the workaround everything is fine, this should really be fixed on the repository.
I have seen that beta5 seems to be published mixed case (with the wrong pom) and all lowercase (which works fine)
In case this is regarding this exact issue, then updating the release notes might be appropriate.

**Comment by derklaro** [comment]
The issue here is that the lib is only destributed via Jitpack. Jitpack is not really nice when it comes to problems like this, I suppose when this lib gets published into a "real" maven repository the issue will be fixed.

**Comment by DasBabyPixel** [comment]
I am not using jitpack though...
https://github.com/DasBabyPixel/NPC-Lib-Demo/blob/68ac91302b97440fde1306e9282769a5f3e67d3a/build.gradle.kts#L7

**Comment by derklaro** [comment]
My repository is a partial jitpack mirror due to the unreliability of jitpack.

**Comment by DasBabyPixel** [comment]
Now that does make sense.
Any time frame on a "real" repository?
Or maybe publishing to central?

**Comment by derklaro** [comment]
Update: I've just published the latest 3.0.0 snapshot to sonatype (repo url is https://s01.oss.sonatype.org/). The project is now using the group id `io.github.juliarn`. Can you let me know if everything works as expected now?

**Comment by DasBabyPixel** [comment]
Everything seems to work correctly now with sonatype.
Might want to add documentation for future reference.

**Comment by derklaro** [comment]
Will do that, thanks for testing! 😄
