### ISSUE TITLE
Don't shade packetevents

### ISSUE THREAD

**Issue by vytskalt** [juliarn/NPC-Lib#114]
I think it would be great if packetevents wasn't shaded in the library and it was up to the user to do so. In my case I already depend on ProtocolLib in my plugin so I don't need packetevents to be included.

**Comment by derklaro** [comment]
I will try to take a look into publishing a version with and one without packetevents shaded soon-ish.

**Comment by portlek** [comment]
@derklaro you can split the packetevents implementation into another module so people can still use that with adding new module's dependency.

**Comment by vytskalt** [comment]
Or it could use `compileOnly` on packetevents and then check at runtime if packetevents is in the classpath. This way it would also be possible to use the standalone packetevents plugin

**Comment by derklaro** [comment]
Starting with beta8 there is no longer anything shaded.
