### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by ghost** [juliarn/NPC-Lib#118]
love this library, pls 1.20 support

**Comment by derklaro** [comment]
There is already full 1.20 support in v3 🙂

**Comment by Panda260** [comment]
also 1.20.4 Support?

**Comment by derklaro** [comment]
Should be, but there might be some new entity poses missing. Everything else should work fine.

**Comment by Cryptite** [comment]
Indeed i haven't had luck with poses in 1.20.4, unsure what's changed.

**Comment by derklaro** [comment]
I've just took a look and entity pose meta is still the same in 1.20.4, except some new poses are missing. Gonna add them later.

**Comment by Cryptite** [comment]
Can you provide a code example on how to use them? Even using old poses, I've tried a few ways to get them to send to players and none seem to work

**Comment by derklaro** [comment]
Well, if you're running 1.20.4, just set the sneak meta. This will indirectly cause a pose update to sneaking.

**Comment by Cryptite** [comment]
Yeah the `sneakingMetaFactory()` one works, but the previous way of providing a `Collection<EntityStatus>` to a `entityStatusMetaFactory()` is what doesn't work.

**Comment by derklaro** [comment]
Weird, a few days ago I've tried to set the elytra flying status without any issues... Can you pass the code snippet you're using to set the entity status?

**Comment by Cryptite** [comment]
```
Collection<EntityStatus> statuses = Set.of(EntityStatus.SWIMMING);
npc.changeMetadata(EntityMetadataFactory.entityStatusMetaFactory(), statuses).schedule(player);
```

**Comment by derklaro** [comment]
Can you try using `FLYING_WITH_ELYTRA`?

**Comment by Cryptite** [comment]
Yeah looks like that works but only when you approach npcs close enough that they turn towards you.
