### ISSUE TITLE
1.20 error

### ISSUE THREAD

**Issue by DevSnx** [juliarn/NPC-Lib#120]
`
Save New Duplicate & Edit Just Text Twitter

[lobby-1][13:21:29 WARN]: io.netty.handler.codec.EncoderException: com.github.juliarn.npclib.relocate.com.packetevents.packetevents.exception.PacketProcessException: Failed to map the Packet ID 113 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.2
[lobby-1][13:21:29 WARN]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[lobby-1][13:21:29 WARN]:       at SimpleCloud-NPC.jar//com.github.juliarn.npclib.relocate.io.packetevents.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[lobby-1][13:21:29 WARN]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[lobby-1][13:21:29 WARN]:       at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140)
[lobby-1][13:21:29 WARN]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[lobby-1][13:21:29 WARN]:       at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[lobby-1][13:21:29 WARN]:       at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[lobby-1][13:21:29 WARN]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[lobby-1][13:21:29 WARN]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[lobby-1][13:21:29 WARN]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[lobby-1][13:21:29 WARN]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[lobby-1][13:21:29 WARN]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[lobby-1][13:21:29 WARN]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[lobby-1][13:21:29 WARN]:       at java.base/java.lang.Thread.run(Thread.java:840)
[lobby-1][13:21:29 WARN]: Caused by: com.github.juliarn.npclib.relocate.com.packetevents.packetevents.exception.PacketProcessException: Failed to map the Packet ID 113 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.2`

**Comment by derklaro** [comment]
Might be due to an old version of packevents, gonna take a look later

**Comment by DevSnx** [comment]
> Might be due to an old version of packevents, gonna take a look later

Okay, server is 1.20.4

**Comment by ZorTik** [comment]
@derklaro Any update on this, please?

**Comment by derklaro** [comment]
packetevents was bumped to the latest release (4.2.0 iirc) in beta7.
