### ISSUE TITLE
Gson packed with npc-lib-bukkit, overwriting other versions

### ISSUE THREAD

**Issue by ZorTik** [juliarn/NPC-Lib#121]
As title suggests, there is a version of Gson packed with `npc-lib-bukkit` version `3.0.0-beta6`. I request moving this somewhere else because it shadows other Gson versions that I use in my project. This version does not support static JsonParser#parseString, so it causes lot errors.
![image](https://github.com/juliarn/npc-lib/assets/67344817/0f0bd734-e23d-4065-b3a7-f6590a88314a)

Also, is there any update to #120 ?

Thank you.

**Comment by derklaro** [comment]
The gson version is no longer bundled as all requirements for it were replaced. Please try with beta7. (However I'm not sure how a gson version bundled in a plugin can overwrite other gson versions? Or as a depenendency... But then you could just exclude the directory).
