### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by DevSnx** [juliarn/NPC-Lib#123]

**Comment by DevSnx** [comment]
![image](https://github.com/user-attachments/assets/5adc02f4-7ccd-4c1e-9a6e-603b56aa0015)

**Comment by derklaro** [comment]
Which npc-lib version are you running?

**Comment by MisterCore** [comment]
I also have the same error. Using Paper 1.20.6 latest build and NPC-Lib v3 Beta 7, also on 1.21

**Comment by derklaro** [comment]
I just re-tested this on 1.21 paper without issues.
