### ISSUE TITLE
npc-lib-bukkit + Paper 1.21.1 

### ISSUE THREAD

**Issue by Farmeurimmo** [juliarn/NPC-Lib#126]
When importing the API in my project, Intellij Ultimate is screaming a lot.

Every spigot line I get things like this
![image](https://github.com/user-attachments/assets/76ee5328-cea7-475c-8f4e-0fcd8c8865f5)

When compiling, I get a lot of those things:
![image](https://github.com/user-attachments/assets/f0c51697-526d-4099-99e2-64e42de28f0f)

I'm using those dependencies:
```xml
<dependency>
     <groupId>io.papermc.paper</groupId>
     <artifactId>paper-api</artifactId>
     <version>1.21-R0.1-SNAPSHOT</version>
     <scope>provided</scope>
</dependency>
<dependency>
     <groupId>io.github.juliarn</groupId>
     <artifactId>npc-lib-bukkit</artifactId>
     <version>3.0.0-beta8</version>
     <scope>compile</scope>
</dependency>
```

**Comment by Farmeurimmo** [comment]
I don't have those errors when I only have paper.

**Comment by derklaro** [comment]
I just tried to reproduce your setup with the attached gradle build file (I don't use maven anymore) & building and importing works fine for me. Maybe this is just an IJ issue or you're using an incompatible java version for compiling?

```groovy
plugins {
    id 'java'
}

group = 'dev.derklaro'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT")
    implementation("io.github.juliarn:npc-lib-bukkit:3.0.0-beta8")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}

```

**Comment by Farmeurimmo** [comment]
I'm using Java 21

**Comment by Farmeurimmo** [comment]
After some tests, if I change the scope to provided, I no longer have errors. But this isn't a solution because the lib in not a plugin on the server (if I'm not wrong, it is the first time I use it and there is not so much docs about how to install and use it)

**Comment by Farmeurimmo** [comment]
When adding to exclusions, I no longer get some of the errors:
![image](https://github.com/user-attachments/assets/bc6de4f8-6589-45f4-8880-ddcfeb028391)

**Comment by Farmeurimmo** [comment]
After some troubles, it is compiling, here is my new dependency in my pom.xml

```xml
<dependency>
            <groupId>io.github.juliarn</groupId>
            <artifactId>npc-lib-bukkit</artifactId>
            <version>3.0.0-beta8</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>examination-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>examination-string</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains</groupId>
                    <artifactId>annotations</artifactId>
                </exclusion>
            </exclusions>
</dependency>
```

**Comment by derklaro** [comment]
Weird. I assume this issue is because the other version is pulled transitevly from a lib in this lib and is marked as a runtime dependency, but I'm confused how maven handles the dependency resolution in that case...

**Comment by Farmeurimmo** [comment]
Yeah
