### ISSUE TITLE
Feature: Documentation

### ISSUE THREAD

**Issue by Farmeurimmo** [juliarn/NPC-Lib#127]
Your API has potential, but it lacks.. documentation as the title says..

I was passing by when I saw your API in a google search.
I hate citizens, but I don't see any other options that can do the job.

Maybe it is in beta, but I don't know who will test it if there is no indication on how it works even if that's temporary.

I tried your API, seem ok and well coded but oh gosh, it is hard to understand how to use some things, it took me 1 hours to figure out some basic stuff that could have taken 10 minutes with a documentation.

![image](https://github.com/user-attachments/assets/b382a598-7710-4120-b9c7-8efb99297c9e)
![image](https://github.com/user-attachments/assets/c0bac319-1423-4d68-abdb-d0e424727c2c)

We don't even know the possibilities of your API easily, I think this is sad.

**Comment by derklaro** [comment]
I'm currently working on documentation & hope to get it out in the next few days. In the meantime you can look into the source of the CloudNet NPC module which uses this API.
NPC Handling: https://github.com/CloudNetService/CloudNet/blob/nightly/modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java

Event Handling: https://github.com/CloudNetService/CloudNet/blob/nightly/modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java

Platform Usage: https://github.com/CloudNetService/CloudNet/blob/nightly/modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java#L92

Hope this helps a bit for now.

**Comment by derklaro** [comment]
I just added documentation and a bunch of code examples into the readme, feel free to leave feedback if something is missing.

**Comment by Cryptite** [comment]
This is great to finally see!
