### ISSUE TITLE
Question: How to change NPC-Name?

### ISSUE THREAD

**Issue by LxkasDEV** [juliarn/NPC-Lib#129]
Hello, i want to know, how to change the Display-Name of an NPC. I want it to look like the first preview picture with a second line and the color fade. I havent found any way of changing the name, since there are no detailed documentations.

**Comment by derklaro** [comment]
The lib is not handling this, you need to do that with armor stand manually (or display entities in modern versions). Only thing you can do is changing the profile name.

**Comment by DasBabyPixel** [comment]
> The lib is not handling this, you need to do that with armor stand manually (or display entities in modern versions). Only thing you can do is changing the profile name.

That's not possible though? You'd need to recreate the NPC to change profile name, wouldn't you?
I just normally use a dummy name with color codes (§1§r, §2§r, §3§r, ...) and use scoreboard teams or hologram armor stands for name tags

**Comment by derklaro** [comment]
Yes, you need to respawn to change the profile name. It's only applicable if your display name is static :)

**Comment by Jxsn-1** [comment]
Is there any way to hide the name?  So you can use holograms without having the name in the way.

**Comment by DasBabyPixel** [comment]
> Is there any way to hide the name? So you can use holograms without having the name in the way.

Use a scoreboard team with nametag visibility set to never

**Comment by Farmeurimmo** [comment]
> > Is there any way to hide the name? So you can use holograms without having the name in the way.
> 
> Use a scoreboard team with nametag visibility set to never

How do you do that? @DasBabyPixel

**Comment by DasBabyPixel** [comment]
[register new team](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Scoreboard.html#registerNewTeam(java.lang.String))
[how to set a team option](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Team.html#setOption(org.bukkit.scoreboard.Team.Option,org.bukkit.scoreboard.Team.OptionStatus))
[the option you want](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Team.Option.html#NAME_TAG_VISIBILITY)
[the option value](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Team.OptionStatus.html#NEVER)
[add NPC name to team](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Team.html#addEntry(java.lang.String))

**Comment by Farmeurimmo** [comment]
Thanks
