### ISSUE TITLE
Help with creating an NPC

### ISSUE THREAD

**Issue by darksider1010** [juliarn/NPC-Lib#26]
Hey, I need help creating an NPC. I implemented the API. I don't see an example on the 
README.md page just that you should create an instance.

In addition, there is not even a list of available events. I would also like to see
examples of how to create an NPC, for example

**Comment by juliarn** [comment]
Hey, maybe this can help you: https://github.com/CloudNetService/CloudNet-v3/blob/ac4ee960d57a1b7eaa7eb460ce0f8e7a848730f5/cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/bukkit/BukkitNPCManagement.java#L212-L237

The NPCPool is an object holding and managing all NPCs, so you create one instance of it for all NPCs. The Pool has to be specified when executing the build-method of the NPC.Builder.

**Comment by darksider1010** [comment]
Thanks you for your answer. The NPC used there is a CloudNPC. Since I'm not using
CloudNET, I can't use a CloudNPC. As I've alerady written, it would be cool if you could
include a few examples. This makes it easier for beginners.

**Comment by juliarn** [comment]
There are now a few examples in the README file (https://github.com/juliarn/NPC-Lib/blob/development/README.md)
