### ISSUE TITLE
NPCs always have Optifine cape when enabling skin layers

### ISSUE THREAD

**Issue by justlunix** [juliarn/NPC-Lib#33]
For some reason, no matter what minecraft user I use, once I enable skin layers, all of them get an optifine cape.

I first thought this is because of me using Optifine, but it even shows to players connected to the server via Geyser who do not use Optifine.

![image](https://user-images.githubusercontent.com/66276367/119566889-f4db4480-bdab-11eb-8fa4-15f2ec508eb8.png)

Why is that and how can this be fixed?

**Comment by juliarn** [comment]
Optifine displays the capes based on the username of the player, so enabling skin layers should show capes, but only when NPCs have the same name a user with an Optifine cape has too.

**Comment by justlunix** [comment]
But why are these capes visible to players without using Optifine? E.g. when I join on the server through Geyser using Minecraft Bedrock Edition.

And, I do not own any optifine cape and neither does any of the players that I've tested this with.

**Comment by justlunix** [comment]
https://github.com/GeyserMC/Geyser/issues/659#issuecomment-696611773

Seems to be related to Geyser Proxy, sorry. Closing
