### ISSUE TITLE
IllegalAccessError im couldn't creating npcs 

### ISSUE THREAD

**Issue by MertUnverdi** [juliarn/NPC-Lib#34]
![image](https://user-images.githubusercontent.com/69310169/120119682-c2fa2180-c1a1-11eb-8c67-af0d99ff389d.png)

**Comment by MertUnverdi** [comment]
I'm tried with development branch

**Comment by juliarn** [comment]
Hey, are you using a recent ProtocolLib version on your server (4.6.0 or newer)? This error seems to be caused by ProtocolLib itself.
