### ISSUE TITLE
Multiple lines

### ISSUE THREAD

**Issue by denmeh** [juliarn/NPC-Lib#56]
Hi, I had in mind to add the availability of having an NPC name with more lines.

So I initially forked the project and started working on it. After that I realized that maybe it was better to have it in a different repository so that I can use it myself as a library in my plugins.

So I made <a href="https://github.com/unldenis/Hologram-Lib">Hologram-Lib</a>, a library that allows you to create holograms (even with items and animations) with packets using ProtocolLib.

If interested I can do a PR to implement my library to create the npcs.

**Comment by lbirkert** [comment]
You cannot make the player name longer then 16 characters or the clients will disconnect

**Comment by denmeh** [comment]
It has nothing to do with the title or even with what I wrote

> You cannot make the player name longer then 16 characters or the clients will disconnect

**Comment by juliarn** [comment]
Hey, very cool project! Altough it isn't really related to npcs, I still think that it might be useful if it is directly implemented into the lib. But I'm not exactly sure yet about the best way it could be integrated.

**Comment by denmeh** [comment]
Yes I had started thinking about it, and the first thing is that I myself use a method in the HologramPool that every 2 ticks does the same job as NpcPool and should share same seeing players etc. So I had in mind to implement the holograms for each npc without the pool, and make public the 'show' and 'hide' methods of the holograms since they are protected at the moment.
