### ISSUE TITLE
Allow skins from URL

### ISSUE THREAD

**Issue by kyngs** [juliarn/NPC-Lib#63]
This was already requested in #46 however, this might currently be possible or at least, citizens seem to be able to achieve it.

[Their Wiki](https://wiki.citizensnpcs.co/Skins)

There, it works by using "/npc skin --url [image]" command, therefore I assume this should also be doable here. I would appreciate it. Can you please take a look at it?

**Comment by derklaro** [comment]
Take a look at https://mineskin.org, I'm currently unsure if we should implement this directly into the lib

**Comment by derklaro** [comment]
Closing as it seems resolved to me, please reopen if you think it is not.

**Comment by kyngs** [comment]
@derklaro I'm sorry, but how is this resolved? I do not see this feature implemented in the latest commits.
BTW. I cannot reopen the issue. If you want I can attempt to implement this myself, and then open a PR.

**Comment by derklaro** [comment]
As I said: You have to implement it yourself using the api I gave you (which is the only way I know to do this kind of stuff) and we will not implement it into the lib.

I closed this as it didn't seem to me that there were any further questions about that topic.
