### ISSUE TITLE
Switch to PacketEvents

### ISSUE THREAD

**Issue by vytskalt** [juliarn/NPC-Lib#65]
I suggest switching from ProtocolLib to [PacketEvents 2.0](https://github.com/retrooper/packetevents/tree/2.0).
It's faster, works with 1.7-1.18, much easier to use and can be shaded instead of requiring ProtocolLib installed on the server.

**Comment by juliarn** [comment]
Hey, thanks for your suggestion, but because of the current api structure, it's not that easy to replace ProtocolLib, as it is referenced in some parts of the api. And it should be possible to relocate and shade ProtocolLib too. Either way the dependency on a library like this is not that great.
