### ISSUE TITLE
Metadata Issue

### ISSUE THREAD

**Issue by Branchyz** [juliarn/NPC-Lib#67]
I'm trying to enable skin layers, but it doesn't work.
I don't understand why, there is no console error.

_I'm using 1.12.2._

This is my code for creating an NPC:

```java
        NPC npc = NPC.builder()
                .profile(this.createProfile(name, skin))
                .location(location)
                .imitatePlayer(false)
                .lookAtPlayer(false)
                .build(this.npcPool);

        npc.metadata().queue(MetadataModifier.EntityMetadata.SKIN_LAYERS, true).send();
```

Is there something I'm doing wrong? Or is this just supposed to work.

_Version: 2.6-RELEASE_

**Comment by derklaro** [comment]
Hey,

the shown code will send the metadata directly after the creation of the npc to all players which are currently connected. The correct way is to set a spawn customiser and send out the metadata to the player the npc is being spawned for.
Hope that helps!

**Comment by Branchyz** [comment]
That helped and now it works.
Thanks for the help and for this lib.

**Comment by derklaro** [comment]
Good to hear!
