### ISSUE TITLE
Skin Layers not showing

### ISSUE THREAD

**Issue by sqcred** [juliarn/NPC-Lib#68]
Hey so i am using the lib on 1.18.2 (nice lib btw)
and i enable skin layers in the show event
any idea why?

**Comment by derklaro** [comment]
Please provide the code which you're using to spawn the npc :)

**Comment by sqcred** [comment]
![carbon (4)](https://user-images.githubusercontent.com/67073397/157071033-1f8699b7-b890-42d1-b176-48a1dfc650cf.png)

**Comment by derklaro** [comment]
I don't see where you enable skin layers for the npc... See #67 (similar issue to this one, but send the skin layer packet instead).

**Comment by sqcred** [comment]
![carbon (5)](https://user-images.githubusercontent.com/67073397/157078870-4b4135bb-b480-4527-88ed-807ddfc38d09.png)
this is beneath it
