### ISSUE TITLE
plugin disable support

### ISSUE THREAD

**Issue by erg43hergeg** [juliarn/NPC-Lib#82]
my onDisable actually looks like this:

`
npcPool.npCs.forEach { npcPool.removeNPC(it.entityId) }
`

1.NPCs do not disappear
2. PlayerNPCHideEvent is called and throws an error because the plugin is already disabled

**Comment by neziw** [comment]
and what's wrong with this? It's normal that event will throw exception if plugin is disabled lol

**Comment by derklaro** [comment]
This issue is fixed in v3 as we're using a custom event bus there which does not rely on the internal bukkit state handling. (From my perspective it's a weird handling to mark a plugin as disabled before it's disabled anyway). I will close this as the issue should is resolved in v3.
