### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by DxsSucuk** [juliarn/NPC-Lib#87]
Asking for a documentation.
For example
- Usage of texture values in a profile (to use custom skins instead of players skin)
- How to genuially destroy the NPCs
- etc.

**Comment by DxsSucuk** [comment]
@derklaro is there documentation planned? Or is there already somesort of one that could allow newer developers to use the api easier without spending most of their time finding out how it works?

For example I would love to use it, but there is not actual documentation that could give me a lead on what I can do and what I can't so I am really looking forward to this!

**Comment by vytskalt** [comment]
You can see some examples here https://github.com/juliarn/NPC-Lib/releases/tag/3.0.0-beta1

**Comment by DxsSucuk** [comment]
There is but its not showing more information, for example how to use a skin texture value instead of an actual player skin?
Is there a right or wrong way to destroy NPCs, are you even able to destroy them? Do you need to use a NPC-Pool? Are there performance gains from doing so?

**Comment by SplotyCode** [comment]
You can use setProperty on `com.github.juliarn.npc.profile.Profile`
Like this:
`profile.setProperty(new Profile.Property("textures", texture, signature));`.
I believe you are forced to use a npc pool

**Comment by mybe** [comment]
This looks like a great resource, but how is there no documentation? A releases page with a couple examples is not documentation.

**Comment by derklaro** [comment]
I just added documentation and a bunch of code examples into the readme, feel free to leave feedback if something is missing.
