### ISSUE TITLE
Leaking Objects of type WrappedWatchableObject

### ISSUE THREAD

**Issue by SplotyCode** [juliarn/NPC-Lib#91]
In `MetadataModifier` we append to metadata but dont remove old `WrappedWatchableObject` with the same index

**Comment by derklaro** [comment]
I don't understand the issue here

**Comment by SplotyCode** [comment]
We change metadata (in this case sneaking) in certain scenarios. Every time we do that a new instance is allocated that never gets released. This results in memory leaks

**Comment by derklaro** [comment]
In v2?

**Comment by SplotyCode** [comment]
In 2.7-SNAPSHOT

**Comment by derklaro** [comment]
I don't think anyone is still maintaining that version as we've focused on developing v3.

**Comment by SplotyCode** [comment]
Is 3.0 considered stable e.g. production ready? I see that the master branch is quite far away from it

**Comment by derklaro** [comment]
It should be - maybe there are some smaller breaking changes coming, but atm there are none I can think about. We're already using this version in [CloudNet](https://github.com/CloudNetService/CloudNet-v3)
