### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by plytki** [juliarn/NPC-Lib#92]
Is there any Maven repo for V3?
I want to include V3 in my project, but I don't know how I am supposed to do it.

**Comment by vytskalt** [comment]
you can include it through jitpack

**Comment by derklaro** [comment]
I mirror the dependency on https://repository.derklaro.dev/ as well if you don't want to rely on jitpack only :)

**Comment by plytki** [comment]
Thank you! I used this repo and dependency and it works:
```
<repository>
            <id>derklaro-repo</id>
            <name>Derklaro-Repository</name>
            <url>https://repository.derklaro.dev/{repository}</url>
</repository>

<dependency>
            <groupId>com.github.juliarn</groupId>
            <artifactId>npc-lib</artifactId>
            <version>3.0.0-beta3</version>
</dependency>
```
