### ISSUE TITLE
Npc flag Npc.LOOK_AT_PLAYER does not work

### ISSUE THREAD

**Issue by phm07** [juliarn/NPC-Lib#94]
When spawning a npc and setting ``.flag(Npc.LOOK_AT_PLAYER, true)``, the npc does not look at the player ingame. Also the npc only becomes visible after calling ``npc.trackPlayer(player)`` and ``npc.addIncludedPlayer(player)`` in ``PlayerJoinEvent``. Maybe the event listener is broken?

My code: https://paste.pauhull.de/xereqifodo.kotlin

Paper version:
``This server is running Paper version git-Paper-404 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f9dc371)``

ProtocolLib version:
``ProtocolLib v5.0.0-SNAPSHOT-b612``

NPC-Lib dependency:
``implementation("com.github.juliarn", "NPC-Lib", "3.0.0-beta3")``

**Comment by derklaro** [comment]
You need to call `.actionController` on the platform builder in order to enable the action controller.
