### ISSUE TITLE
Npc Rotation Issue

### ISSUE THREAD

**Issue by plytki** [juliarn/NPC-Lib#97]
Npc yaw setting is not working. It always spawns at yaw = 0.
I used `npc.lookAt()` but still doesn't work.
How to properly rotate an Npc?

**Comment by derklaro** [comment]
Interesting, the method is used internally (in combination with the action controller) and works there perfectly fine from my testing 🤔

**Comment by plytki** [comment]
Maybe I'm doing it wrong. How can I properly rotate the npc and when should I?

**Comment by plytki** [comment]
![image](https://user-images.githubusercontent.com/53957038/221382483-d1148650-19ab-422d-863f-23bbc18f53ba.png)
I've tried everything.

**Comment by ytnoos** [comment]
I have the same issue

**Comment by plytki** [comment]
![image](https://user-images.githubusercontent.com/53957038/221382787-ba1e5d43-6613-441d-9f2a-3d1ae12fce03.png)
Line 128 is setting the position but still nothing.

**Comment by derklaro** [comment]
The `lookAt` method returns a prepared packet, you need to send it to the target player(s), using `.schedule`

**Comment by plytki** [comment]
This also does not work. "/ 
https://streamable.com/273clz

**Comment by derklaro** [comment]
Can you print out the result of `bossNPC.getPosition()` and walk to that position? That should be where the npc looks to...

**Comment by plytki** [comment]
https://streamable.com/jnspvf

**Comment by derklaro** [comment]
Based on the printed values, it looks correct? (maybe I'm just misunderstanding the values tho 😂 )

**Comment by plytki** [comment]
Npcs are facing yaw 0. Not 90 as expected. 
![image](https://user-images.githubusercontent.com/53957038/221428460-8fb55e10-cab8-486a-a477-b2551a8f760b.png)

**Comment by derklaro** [comment]
The yaw and pitch you're providing to the method are not taken into account. The method calculates the yaw and pitch to look at based on the position to look at (x, y, z).

**Comment by plytki** [comment]
Is there a way to change just rotation? I want to just change the rotation of the npc.

**Comment by derklaro** [comment]
Might be a good helper method to add, until then you can use `platform.packetFactory().createRotationPacket(yaw, pitch).schedule(...)`

**Comment by plytki** [comment]
Ok, that works! Thanks!
